Controllers/userController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyChoice.Models;

namespace MyChoice.Controllers
{
    public class userController : Controller
    {
        // GET: user
        public ActionResult Index()
        {
            return RedirectToAction("ListAllTrees", "Tree");
        }

        public ActionResult AllTree()
        {
            return RedirectToAction("ListAllTrees");
        }

        public string ListAllTrees()
        {
            return @"<ul>
            <li>Maple</li>
            <li>Palm</li>
            <li>Birch</li>
            <li>Cedar</li>
            </ul>";
        }

        public ActionResult NewTree(string TreeName, string State, int Price, int Age, string Season, bool IsFavorite)
        {
            treeModel t = new treeModel()
            {
                treeName = TreeName,
                state = State,
                price = Price,
                age = Age,
                season = Season,
                isFavorite = IsFavorite
            };
            return View("ConfirmTree", t);
        }

        [HttpPost]
        public ActionResult NewTrees(string treeName, string state, int price)
        {
            ViewBag.Message = "Tree Name:" + treeName + " " + "State Name:" + state;
            ViewBag.Message = "The Price" + price;
       
            return View("confirmTree");
        }
        public ActionResult NewTrees()
        {
            return View("NewTree");
        }
        public ActionResult HomePage()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trees for Bees</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            padding-top: 0px;
        }

        .navbar a:link {
            color: white;
        }

        .navbar a:visited {
            color: blue;
        }

        .navbar a:hover {
            color: lightgoldenrodyellow;
            text-shadow: 1px 1px white;
            transition: 1s;
            text-decoration: none;
            font-size: 1.2em;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" href="#">Trees 4 Bees</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("About", "About", "Home")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Contact", "Contact", "Home")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("All Trees", "AllTree", "user")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("New Tree", "NewTrees", "user")
                    </li>
                    <li class="nav-item nav-link">
                        @Html.ActionLink("Home Page", "HomePage", "user")
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>